#!/bin/bash

echo "🚀 Starting Airbash Test Suite..."

# First, install airbash to create necessary scripts
echo "📦 Installing Airbash..."
bash install.sh

# Create test environment with virtual WiFi
export TEST_INTERFACE="hwsim0"

# Load mac80211_hwsim module for virtual wireless interfaces
echo "🔧 Setting up virtual wireless environment..."
sudo modprobe mac80211_hwsim radios=3 2>/dev/null || echo "mac80211_hwsim may already be loaded or unavailable"

# Wait for interfaces to be created
sleep 2

# Set up network namespace for isolated testing
sudo ip netns add airbash_test 2>/dev/null || echo "Network namespace may already exist"
sudo ip netns exec airbash_test ip link set lo up

# Move virtual interfaces to test namespace
for iface in wlan0 wlan1 wlan2; do
    if ip link show $iface &>/dev/null; then
        sudo ip link set $iface netns airbash_test 2>/dev/null || true
    fi
done

# Configure virtual access point in test namespace - default key generated by upc_keys.c
echo "📡 Setting up virtual access point..."
sudo ip netns exec airbash_test hostapd -B /dev/stdin << EOF
interface=wlan0
driver=nl80211
ssid=UPC1234567
channel=1
hw_mode=g
wpa=2
wpa_key_mgmt=WPA-PSK
wpa_pairwise=CCMP
wpa_passphrase=CWGUJAJX
EOF

# Wait for AP to start
sleep 3

# Configure virtual client to connect and disconnect (simulating deauth scenario)
echo "📱 Setting up virtual client..."
sudo ip netns exec airbash_test wpa_supplicant -B -i wlan1 -c /dev/stdin << EOF
network={
    ssid="UPC1234567"
    psk="CWGUJAJX"
}
EOF

# Wait for connection
sleep 5

# Now run airbash in the test environment with limited scan time
echo "⚡ Running Airbash in test environment..."
sudo ip netns exec airbash_test timeout 90s ./airba.sh || echo "Airbash test completed (may have timed out as expected)"

# Test the database creation
sqlite3 .database.sqlite3 "SELECT name FROM sqlite_master WHERE type='table';" | grep captures

# Compile the UPC keys module
gcc -O2 -o modules/upckeys modules/upc_keys.c -lcrypto

# Test crackdefault.sh with a simulated database entry
sqlite3 .database.sqlite3 "INSERT INTO captures (bssid, essid, pmkid, processed) VALUES ('02:00:00:00:01:00', 'UPC1234567', 'test_pmkid', 0);"

# Test the UPC module default cracking
echo "🔍 Testing UPC module cracking..."
bash src/crackdefault.sh | grep -q "Key found" && echo "✅ UPC module cracking works!"

# Cleanup test environment
echo "🧹 Cleaning up test environment..."
sudo pkill hostapd || true
sudo pkill wpa_supplicant || true
sudo ip netns delete airbash_test || true
sudo rmmod mac80211_hwsim 2>/dev/null || true

# Check if any captures were made
if [ -d ".output" ] && [ "$(ls -A .output 2>/dev/null)" ]; then
    echo "✅ Airbash successfully captured data in test environment!"
    ls -la .output/
else
    echo "ℹ️  No captures found - this may be expected in a simulated environment"
fi

echo "🎯 Airbash security testing suite completed successfully!"